---
- name: Set the green LED trigger to '{{ green_led_setting }}'
  ansible.builtin.shell: echo {{ green_led_setting }}| tee /home/mpi/LEDs/green_led/trigger

- name: Set the blue LED trigger to '{{ blue_led_setting }}'
  ansible.builtin.shell: echo {{ blue_led_setting }}| tee /home/mpi/LEDs/blue_led/trigger
...
