openblas_repo: "https://github.com/OpenMathLib/OpenBLAS.git"
openblas_clone_dest: "/home/mpi/OpenBLAS"
openblas_install_path: "/opt/openblas"
release_version: "v0.3.30"
environment_variables:
  OMP_NUM_THREADS: "1"
  OPENBLAS_NUM_THREADS: "1"
  LD_LIBRARY_PATH: "{{ openblas_install_path  }}/lib:$LD_LIBRARY_PATH"
