---
- name: Disable unnecessary services for OpenMPI cluster
  become: true
  block:
    - name: Disable unnecessary services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - rsyslog.service
        - systemd-journald.service
        - cron.service
        - wpa_supplicant.service
...
